parameters:
  cmake_args: ''

steps:
- script: |
    cat /proc/cpuinfo
  displayName: /proc/cpuinfo
  condition: succeededOrFailed()

- script: |
    mkdir build
    cd build
    cmake -L -GNinja .. ${{ parameters.cmake_args }}
  env:
    TESTS_SUFFIX: ${{ parameters.suite_label_suffix }}
  displayName: CMake

- script: ninja
  displayName: Ninja
  workingDirectory: build
  env:
    CCACHE_DIR: /ccache
