steps:
- script: |
    mkdir install
    ninja install
  workingDirectory: build
  displayName: 'Install CCF locally'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(Build.SourcesDirectory)/build/install # TODO: Install directory
    archiveType: 'tar'
    tarCompression: 'gz'
    archiveFile: '$(Build.ArtifactStagingDirectory)/ccf_install_${{ parameters.protocol }}.tar.gz'
    verbose: true
  displayName: 'Archive CCF installation'

- task: PublishPipelineArtifact@1
  inputs:
    path: $(Build.ArtifactStagingDirectory)/ccf_install.tar.gz
    artifact: ccf_install.tar.gz
    displayName: 'Publish CCF installation as build artifact'